trigger:
- master

variables:
- group: CustodianCoreCI
- name: WINDOWS_CACHE_DIR
  value: $(LOCALAPPDATA)\pip\cache

jobs:


- job: 'CustodianCask'
  displayName: 'Container Cask'
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:
  - task: GoTool@0
    inputs:
      version: '1.12.6'

  - script: make release
    workingDirectory: tools/cask/
    displayName: 'Build for all platforms'
