trigger:
- master

variables:
- group: CustodianCoreCI

jobs:

- job: 'CustodianDockerBuild'
  displayName: 'Docker Build'
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - checkout: self
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
      architecture: 'x64'
  # bin directory is in .dockerignore
  - script: |
    echo "Docker CI is now done in Github Actions'
