build:
  image: python:2-alpine
  environment:
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=someome
    - AWS_SECRET_ACCESS_KEY=something
  commands:
    - pip install -r requirements-dev.txt
    - python setup.py develop
#    - flake8 maid --ignore=W293,W291,W503,W391
    - nosetests -s -v tests
