build:
  image: python:2-alpine
  environment:
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
  commands:
    - mkdir cache
    - pip install -r requirements-dev.txt --cache-dir=cache
    - python setup.py develop
    - nosetests -s -v tests
