language: python
cache:
  pip: true
env:
  - C7N_TEST_WORKERS=8

matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true

install:
  - pip install coveralls tox
script:
  - TOXENV=`tools/dev/citoxenv.py` tox
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then coveralls; fi
