name: 'Build and Publish Docker Image'
description: 'Build and Publish Docker Image'
inputs:
  dockerfile:
    description: 'Dockerfile to build'
    required: true
  repository:
    description: 'docker hub repository'
    required: true
  image:
    description: 'image'
    required: true
  name:
    description: 'image name'
    required: true
  description:
    description: 'image description'
    required: true
  tag_prefix:
    description: 'tag prefix'
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ env.HUB_USER }}
        password: ${{ env.HUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ inputs.repository }}/${{ inputs.image }}
        labels: |
          org.opencontainers.image.created={{date YYYY-MM-DD}}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.documentation=https://cloudcustodian.io/docs
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.description=${{ inputs.description }}
        tags: |
          type=raw,value=${{ inputs.tag_prefix }}latest
          type=semver,pattern={{raw}}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.dockerfile }}

    - name: scan
      shell: bash
      run: |
        wget -q -O bin/trivy.tgz https://github.com/aquasecurity/trivy/releases/download/v0.5.4/trivy_0.5.4_Linux-64bit.tar.gz
        cd bin && tar xzf trivy.tgz
        ./trivy  ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag_prefix}}latest
        cd ..

    - name: test
      shell: bash
      run : |
        curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - -y --version 1.1.14
        python -m venv .
        . bin/activate && poetry install
        IMAGE_NAME =  ${{ inputs.name }}
        # set it to uppercase
        IMAGE_NAME = ${IMAGE_NAME^^}
        . bin/activate && TEST_DOCKER=yes \
                          CUSTODIAN_${IMAGE_NAME}_IMAGE=${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag_prefix }}latest \
                          pytest -p no:terraform -v tests/test_docker.py

    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.dockerfile }}
