

---

apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: create-namespace
deploy:
  kubectl:
    manifests:
      - .skaffold/namespace.yaml

---
apiVersion: skaffold/v2beta29
kind: Config
requires:
  - configs: [create-namespace]
metadata:
  name: deploy
build:
  artifacts:
  - context: ../../
    docker:
      dockerfile: ../../docker/c7n-kube
    image: c7n-kube

deploy:
  kubectl:
    defaultNamespace: c7n-system
    manifests:
      - .skaffold/templates/*.yaml

  helm:
    flags:
      global:
        - "--debug"
    releases:
      - artifactOverrides:
          controller.image: c7n-kube
        name: c7n-kube
        remoteChart: https://github.com/cloud-custodian/helm-charts/releases/download/c7n-kube-0.1.1/c7n-kube-0.1.1.tgz
        imageStrategy:
          fqn: {}
        namespace: c7n-system
        valuesFiles:
          - .skaffold/values.yaml
