variables:
- group: CustodianCoreCI

jobs:
- job: 'azure_nightly_test_run'
  displayName: 'Azure Nightly Test Run'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 1

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: python -m pip install --upgrade pip && pip install . && pip install -r requirements-dev.txt
      displayName: "Install Dependencies"