name: "CI"

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint Check
        run: |
          make lint

  Tests:
    runs-on: "${{ matrix.os }}"
    needs: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Bootstrap poetry
        shell: bash
        run: |
          curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py \
            | python - -y --version 1.1.8

      - name: Set up cache
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        shell: bash
        run: timeout 10s poetry run pip --version || rm -rf .venv

      - name: Virtualenv
        shell: bash
        run: |
          echo $OSTYPE
          if [[ -d .venv ]]
          then
             echo "cached virtualenv"
          else
             python -m venv .venv
          fi

      - name: Update PATH
        shell: bash
        run: |
          if [[ "$OSTYPE" == "msys" ]]
          then
            echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH
            echo "$PWD\.venv\bin" >> $GITHUB_PATH
            echo "VIRTUAL_ENV=$PWD\.venv" >> $GITHUB_ENV
          else
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            echo "$PWD/.venv/bin" >> $GITHUB_PATH
            echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          fi

      - name: Install Deps
        run: |
          echo `which pip`
          echo `which poetry`
          pip install -U pip
          pip install -U wheel
          make install-poetry

      - name: Test
        run: |
          . test.env && poetry run python -m pytest -n auto -p no:sugar -q tests tools

      - name: License Check
        if: contains(matrix.python-version, '3.9')
        run: |
          poetry run python tools/dev/license-check.py
