name: "Docker Build CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: c7n build and test
        uses: ./.github/composites/docker-build-push
        env:
          HUB_USER: c7nbuild
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        with:
          name: c7n
          push: false
          platforms: linux/amd64
