name: "Functional"

env:
  terraform_version: "1.2.8"
  C7N_FUNCTIONAL: true

on:
  push:
    branches:
      - functional-testing

jobs:
  AWS:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::532725030595:role/GithubActionsTest
          aws-region: us-east-1

      - name: Install Terraform
        run: |
          wget -q https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip
          unzip -qq terraform*.zip
          mv terraform /usr/local/bin
          mkdir -p .tfcache

      - name: Install Requirements
        run: |
          pip install --cache-dir=./.pip-cache -r requirements.txt

      - name: Test
        run: |
          pytest tests -m "not skiplive" -m terraform -n auto --junit-xml=report-aws.xml

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.3.3
        if: always()
        with:
          report_paths: 'report-aws.xml'


  GCP:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/18998076121/locations/global/workloadIdentityPools/github-actions-pool'
          service_account: 'github-actions@sonny-sandbox.iam.gserviceaccount.com'

      - name: Install Terraform
        run: |
          wget -q https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip
          unzip -qq terraform*.zip
          mv terraform /usr/local/bin
          mkdir -p .tfcache

      - name: Install Requirements
        run: |
          pip install -qr requirements.txt
          python setup.py -q install
          cd tools/c7n_gcp
          pip install -r requirements.txt
          python setup.py -q install
          pip install git+https://github.com/cloud-custodian/pytest-terraform.git@better-logging

      - name: Test
        run: |
          pwd
          pytest tests -s -v --junit-xml=report-gcp.xml -m terraform -n auto

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.3.3
        if: always()
        with:
          report_paths: 'report-gcp.xml'
